services:
  cockpit:
    image: bluerobotics/cockpit:v1.0.2
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY} # Can be commented out if not used
      - PULSE_SERVER=${PULSE_SERVER} # Can be commented out if not used
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - ros2_backend

  mavlink2rest:
    image: patrickelectric/mavlink2rest
    ports:
      - 8088:8088
      - 14551:14551
      - 14550:14550
    environment:
      - MAVLINK_SRC="udpin:blue:14550"
      - SERVER_PORT="0.0.0.0:8088"
    networks:
      - ros2_backend

networks:
  ros2_backend:
    external: true
