services:
  blue:
    image: ghcr.io/${BLUE_GITHUB_REPO:?Github repo not set}:${BLUE_ROS_DISTRO:?BLUE_ROS_DISTRO not set}-desktop
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY} # Can be commented out if not used
      - PULSE_SERVER=${PULSE_SERVER} # Can be commented out if not used
    network_mode: host
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../../bluerov_deployment:/home/ubuntu/ws_blue/src/bluerov_deployment
      - ../../../auv_controllers:/home/ubuntu/ws_blue/src/auv_controllers
      - ../../../mobile_to_maritime:/home/ubuntu/ws_blue/src/mobile_to_maritime
      - ../../../blue:/home/ubuntu/ws_blue/src/blue
    # Launch sim directly
    entrypoint: [ "/bin/bash", "-i", "-c" ]
    command: [ "ros2 launch blue_demos bluerov2_demo.launch.yaml use_sim:=true" ]

  zenoh:
    image: eclipse/zenoh-bridge-ros2dds:latest
    ports:
      - 7447:7447
      - 7448:7448
    environment:
      ROS_DOMAIN_ID: 0
      ROS_DISTRO: ${BLUE_ROS_DISTRO}

  foxglove-bridge:
    image: ghcr.io/apl-ocean-engineering/blue-foxglove-bridge-docker:${BLUE_ROS_DISTRO}
    ports:
      - 8765:8765

